import type { Metadata } from "next";
import {
  Lexend,
  Bangers,
} from "next/font/google";
import "./globals.css";
import AppBgImg from "@/components/background";

const lexend = Lexend({ subsets: ["latin"] });
const bangers = Bangers({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-bangers",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <meta
        name="viewport"
        content="width=device-width, initial-scale=1.0, user-scalable=no"
      ></meta>
      <body
        className={`${lexend.className} ${bangers.variable}`}
      >
        <AppBgImg />
        {children}
      </body>
    </html>
  );
}
